### ISSUE TITLE
Incorrect State Representation in the Toggle Button in the Upper Right Corner

### ISSUE THREAD

**Issue by SeaSoonKeun** [tunogya/abandonai-app#11]
![image](https://github.com/tunogya/abandonai-app/assets/82697297/147212ca-89eb-4c0f-be71-20261e9908b3)

The toggle button in the upper right corner of the interface displays an incorrect state. It should represent the state of GPT-4, with the default state being GPT-4 closed. Clicking the button should toggle the state accordingly.

**Comment by tunogya** [comment]
You are right!
