### ISSUE TITLE
Why ChatGPT-4 can't search on Internet and upload PDF file

### ISSUE THREAD

**Issue by cainiaoYJ** [tunogya/abandonai-app#13]

**Comment by tunogya** [comment]
We will add the function of pdf upload soon. Please wait patiently. The current version already includes Google search. It will automatically open during the conversation and does not require you to organize the search content. For example, this question: “What is the news about Bitcoin today? It is necessary to search online.”

**Comment by tunogya** [comment]
By the way, if you want to use the search function, remember to disable Vision mode and only enable GPT4. This is a current limitation of the model.
