### ISSUE TITLE
Clear the current session unexpectedly

### ISSUE THREAD

**Issue by SeaSoonKeun** [tunogya/abandonai-app#6]
Clicking on the history record on the left side will clear the current session without saving, resulting in the loss of records.

**Comment by tunogya** [comment]
> Clicking on the history record on the left side will clear the current session without saving, resulting in the loss of records.点击左侧历史记录会清除当前会话而不保存，导致记录丢失。

We have made efforts to reduce the response delay of the SQS queue. If a session has just been created recently, it will not update the historical records in a short period of time. Try refreshing the page first.

Recently, we will try to use socket connection to replace the 3-second uninterrupted polling of historical records.

**Comment by tunogya** [comment]
Apologize. We found the root cause of eating chat, which comes from our sorting function.

We used nanoid as the [sorting key](https://docs.aws.amazon.com/zh_cn/amazondynamodb/latest/developerguide/bp-sort-keys.html) for chat, but it is random.

**Comment by tunogya** [comment]
Now, we have dysortid!
