### ISSUE TITLE
Feature Request: Add functionality to download audio responses for easy sharing

### ISSUE THREAD

**Issue by SeaSoonKeun** [tunogya/abandonai-app#8]
Expected Behavior
After an audio response is generated, there should be a clear and accessible option to download the file in a standard audio format (e.g., mp3, wav). This option would allow users to save the audio on their devices and share it with others outside the platform.

Actual Behavior
Currently, users can only listen to the audio responses on the platform. There is no feature to download the audio files.

Possible Solution
Implement a download button or link next to the audio response player. The backend service could generate a downloadable file and provide it to the user upon request.

Additional Context
The ability to download and share audio responses can be particularly useful for educational purposes, presentations, or simply for sharing interesting content on social media platforms.

**Comment by tunogya** [comment]
Now, we have a download button.
